apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staging-ingress
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod   # ðŸ”¹ Reference staging ClusterIssuer
spec:
  tls:
  - hosts:
    - qatalyst.tech   # ðŸ”¹ Replace with your domain
    secretName: staging-tls # ðŸ”¹ Secret will be created automatically
  rules:
  - host: qatalyst.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kf-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: kf-backend-service
            port:
              number: 80
              
  - host: subsite.qatalyst.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress-service
            port:
              number: 80
